### ISSUE TITLE
Archlinux(KDE): X Error of failed request:  BadWindow (invalid Window parameter) 

### ISSUE THREAD

**Issue by zbqhc** [bestwu/docker-wechat#29] opened 2020-12-28 03:06 UTC
```
$ xhost +
access control disabled, clients can connect from any host

$ docker run --rm --name wechat --device /dev/snd --ipc=host \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v $HOME/WeChatFiles:/WeChatFiles \
-e DISPLAY=unix$DISPLAY \
-e XMODIFIERS=@im=ibus \
-e QT_IM_MODULE=ibus \
-e GTK_IM_MODULE=ibus \
-e AUDIO_GID=`getent group audio | cut -d: -f3` \
-e GID=`id -g` \
-e UID=`id -u` \
bestwu/wechat
启动 WeChat
Run Deepin-WeChat 2.6.8.65deepin0 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,16 CPUs Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (A0655),ASM,AES-NI)

Scanning the drive for archives:
1 file, 50232547 bytes (48 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-WeChat/files.7z
--
Path = /opt/deepinwine/apps/Deepin-WeChat/files.7z
Type = 7z
Physical Size = 50232547
Headers Size = 9283
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 109
Files: 976
Size:       156938730
Compressed: 50232547
total 0
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 c: -> ../drive_c
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com1 -> /dev/ttyS0
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com10 -> /dev/ttyS9
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com11 -> /dev/ttyS10
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com12 -> /dev/ttyS11
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com13 -> /dev/ttyS12
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com14 -> /dev/ttyS13
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com15 -> /dev/ttyS14
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com16 -> /dev/ttyS15
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com2 -> /dev/ttyS1
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com3 -> /dev/ttyS2
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com4 -> /dev/ttyS3
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com5 -> /dev/ttyS4
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com6 -> /dev/ttyS5
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com7 -> /dev/ttyS6
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com8 -> /dev/ttyS7
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com9 -> /dev/ttyS8
lrwxrwxrwx 1 wechat wechat  8 12月 28 11:01 d:: -> /dev/sdb
lrwxrwxrwx 1 wechat wechat 17 12月 28 11:01 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 wechat wechat  9 12月 28 11:01 e:: -> /dev/sdb1
lrwxrwxrwx 1 wechat wechat 12 12月 28 11:01 y: -> /home/wechat
lrwxrwxrwx 1 wechat wechat  1 12月 28 11:01 z: -> /
total 0
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 c: -> ../drive_c
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com1 -> /dev/ttyS0
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com10 -> /dev/ttyS9
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com11 -> /dev/ttyS10
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com12 -> /dev/ttyS11
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com13 -> /dev/ttyS12
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com14 -> /dev/ttyS13
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com15 -> /dev/ttyS14
lrwxrwxrwx 1 wechat wechat 11 12月 28 11:01 com16 -> /dev/ttyS15
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com2 -> /dev/ttyS1
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com3 -> /dev/ttyS2
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com4 -> /dev/ttyS3
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com5 -> /dev/ttyS4
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com6 -> /dev/ttyS5
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com7 -> /dev/ttyS6
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com8 -> /dev/ttyS7
lrwxrwxrwx 1 wechat wechat 10 12月 28 11:01 com9 -> /dev/ttyS8
lrwxrwxrwx 1 wechat wechat  8 12月 28 11:01 d:: -> /dev/sdb
lrwxrwxrwx 1 wechat wechat 17 12月 28 11:01 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 wechat wechat  9 12月 28 11:01 e:: -> /dev/sdb1
lrwxrwxrwx 1 wechat wechat 12 12月 28 11:01 y: -> /home/wechat
lrwxrwxrwx 1 wechat wechat  1 12月 28 11:01 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/home/wechat/.deepinwine/Deepin-WeChat/drive_c/users/wechat/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2020年 12月 28日 星期一 11:01:01 UTC:kill WeChat.exe block
2020年 12月 28日 星期一 11:01:01 UTC:No wine process found
/home/wechat/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
Starting process c:/Program Files/Tencent/WeChat/WeChat.exe ...
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  10
  Current serial number in output stream:  10
```

**Comment by zbqhc** [comment] 2020-12-28 03:19
同样的环境可以正常显示gui的libreoffice
```
docker run -d  -v /etc/localtime:/etc/localtime:ro  \
-v /tmp/.X11-unix:/tmp/.X11-unix  \
-e DISPLAY=unix$DISPLAY  \
-e GDK_SCALE  \
-e GDK_DPI_SCALE  \
--name libreoffice  \
jess/libreoffice
```

**Comment by bestwu** [comment] 2020-12-28 04:35
Duplicate of #24

**Closed** 2020-12-28 05:18 UTC
